#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep -q '^VGA-1 connected'; then
    xrandr --output VGA-1 --primary --mode 1366x768 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of VGA-1
    bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9 10
    bspc monitor VGA-1 -d 1
else
    bspc monitor eDP-1 -d 1 2
    bspc monitor HDMI-1 -d III IV V VI VII VIII IX X
fi

# if [[ $(xrandr -q | grep 'VGA-1 connected') ]]; then
# xrandr --output eDP-1 --primary --mode 1920x1200 --rotate normal --output HDMI-1 --mode 3840x2160 --rotate normal --left-of eDP-1
# bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9 0
# bspc monitor eDP-1 -d 1
# else
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# fi

$HOME/.config/polybar/launch.sh

nitrogen --restore & > /dev/null &
picom --backend xrender > /dev/null &

############ Dracula theme ##################
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
############################################

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a brave-browser desktop='^2'
bspc rule -a firefox desktop='^5'
bspc rule -a Emacs state=tiled
bspc rule -a emacsclient state=tiled
