#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

nitrogen --restore & > /dev/null &
picom & > /dev/null &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Emacs state=tiled
bspc rule -a emacsclient state=tiled
